### ISSUE TITLE
Handle ZIP data sources

### ISSUE THREAD

**Issue by space-buzzer** [COVID19Tracking/covid19-datafetcher#4]
Some states have links to their data in in a .zip file. There's no code to fetch and parse these yet

**Comment by dbfreem** [comment]
@space-buzzer is this still a needed feature? If so I might be able to help out if a few more details of the request where provided. Like an example of a state website that published zip archives.

**Comment by space-buzzer** [comment]
Hi, thanks!
MA publishes zip files. I added the support, and for now use it just for them (as zipped folders).
I need to clean up and update the issues here :sweat_smile:

**Comment by dbfreem** [comment]
@space-buzzer let me know if there are any items you need help on and I will take a look. I saw some TODOs laying around but wasn't sure what priorities were on any of them.

**Comment by space-buzzer** [comment]
Oh nice, thanks so much!
I'll clean up some issues and TODOs this weekend

**Comment by dbfreem** [comment]
@space-buzzer I had put in a PR for a fix to an issue with the zip archive implementation but then noticed the project didnt't have an open source license. So I closed the PR.  Is there any intent to add an open source license so that it makes it easier for others to contribute.
